version: "3.7"
services:
  web:
    image: c2dhunilu/marugoto-frontend:latest
    volumes:
      - ./data/marugoto/contents/ranketwo/resources:/usr/share/nginx/html/ranketwo
    ports:
      - 8088:80
  backend:
    image: uzhlit/marugoto:latest
    volumes:
      - ./config/application-production.properties:/usr/local/tomcat/conf/application-production.properties
      - ./data/marugoto/contents/ranketwo/resources:/resources
    environment:
      - JAVA_OPTS="-Dspring.config.location=file:/usr/local/tomcat/conf/application-production.properties"
    ports:
      - 8080:8080
  shell:
    image: uzhlit/marugoto-shell:latest
    volumes:
      - ./config/application-production.properties:/etc/application-production.properties
      - ./data/marugoto/contents:/home
  database:
    image: arangodb:3.3
    volumes:
      - ./data/arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
